# Generated by Django 4.0.1 on 2022-04-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malaria',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
